version: '3'

services:
  bipolar-server:
    container_name: "bipolar-server"
    build: .cloud/docker
    image: bipolar
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    container_name: "bipolar-mysql"
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=bipolar_db
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  nginx:
    container_name: "bipolar-nginx"
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - bipolar-server